#!/usr/bin/env python
# -*- coding: US-ASCII -*-
#
# generated by wxGlade not found on Tue Jul 18 10:10:25 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Dialog_snapshot(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_snapshot.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Nombre:")
        self.nombre_snap = wx.TextCtrl(self, -1, "")
        self.label_2 = wx.StaticText(self, -1, u"Descripci\u00f3n:")
        self.descripcion_snap = wx.TextCtrl(self, -1, "")
        self.checkbox_memory = wx.CheckBox(self, -1, "memory")
        self.checkbox_quiesce = wx.CheckBox(self, -1, "quiesce")
        self.snap_ok = wx.Button(self, -1, "OK")
        self.snap_cancel = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_snapshot.__set_properties
        self.SetTitle("dialogo_snapshot")
        self.nombre_snap.SetMinSize((300, 20))
        self.descripcion_snap.SetMinSize((300, 20))
        self.checkbox_memory.SetValue(1)
        self.snap_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_snapshot.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(4, 2, 10, 10)
        grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.nombre_snap, 0, 0, 0)
        grid_sizer_2.Add(self.label_2, 0, 0, 0)
        grid_sizer_2.Add(self.descripcion_snap, 0, 0, 0)
        grid_sizer_2.Add(self.checkbox_memory, 0, 0, 0)
        grid_sizer_2.Add(self.checkbox_quiesce, 0, 0, 0)
        grid_sizer_2.Add(self.snap_ok, 0, wx.ALIGN_RIGHT | wx.RIGHT, 0)
        grid_sizer_2.Add(self.snap_cancel, 0, 0, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_2.Add(grid_sizer_2, 1, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Dialog_snapshot

class Dialogo_texto(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialogo_texto.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.salida_texto = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.bnt_salida_ok = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialogo_texto.__set_properties
        self.SetTitle("dialogo_texto")
        self.SetSize((575, 214))
        self.salida_texto.SetMinSize((391, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialogo_texto.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.salida_texto, 0, wx.ALL | wx.EXPAND, 4)
        sizer_1.Add(self.bnt_salida_ok, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.RIGHT, 5)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class Dialogo_texto

class Dialogo_user_pass(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialogo_user_pass.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "Usuario:")
        self.usuario = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "Password:")
        self.password = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.button_OK = wx.Button(self, -1, "OK")
        self.button_cancel = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialogo_user_pass.__set_properties
        self.SetTitle("user_pass")
        self.usuario.SetMinSize((300, 20))
        self.label_4.Hide()
        self.password.SetMinSize((300, 20))
        self.password.Hide()
        self.button_OK.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialogo_user_pass.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.usuario, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.password, 0, 0, 0)
        grid_sizer_1.AddGrowableCol(0)
        sizer_3.Add(grid_sizer_1, 1, wx.ALIGN_CENTER | wx.ALIGN_RIGHT | wx.ALL | wx.EXPAND, 10)
        grid_sizer_4.Add(self.button_OK, 0, 0, 0)
        grid_sizer_4.Add(self.button_cancel, 0, wx.ALIGN_RIGHT, 0)
        sizer_3.Add(grid_sizer_4, 1, wx.ALIGN_RIGHT | wx.ALL, 4)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Dialogo_user_pass

class Dialogo_ejecutando(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialogo_ejecutando.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.titulo = wx.StaticText(self, -1, "Accediendo al sistema: ", style=wx.ALIGN_CENTER)
        self.elementos = wx.StaticText(self, -1, "000000", style=wx.ALIGN_CENTER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialogo_ejecutando.__set_properties
        self.SetTitle("Ejecutando...")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialogo_ejecutando.__do_layout
        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(self.titulo, 0, wx.ALIGN_CENTER | wx.ALL, 4)
        grid_sizer_3.Add(self.elementos, 0, wx.ALIGN_CENTER | wx.ALL, 4)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Dialogo_ejecutando

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_5 = wx.StaticText(self, -1, "Cadena Busqueda:")
        self.text_ctrl_bucar = wx.TextCtrl(self, -1, "")
        self.button_buscar = wx.Button(self, -1, "Buscar")
        self.label_6 = wx.StaticText(self, -1, "total VM: 333")
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap("/Users/wbug/Documents/pyvmwareclient/wxglade/recicla.png", wx.BITMAP_TYPE_ANY))
        self.list_ctrl_1 = wx.ListCtrl(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.text_ctrl_bucar.SetMinSize((200, 20))
        self.button_buscar.SetMinSize((85, 40))
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.text_ctrl_bucar, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 7)
        sizer_5.Add(self.button_buscar, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_5.Add(self.bitmap_button_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_5, 1, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 6)
        sizer_4.Add(self.list_ctrl_1, 1, 0, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class _406005006_Dialogo_acceso_vcenter(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: _406005006_Dialogo_acceso_vcenter.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.text_ctrl_3 = wx.TextCtrl(self, -1, "")
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "")
        self.Exit = wx.ToggleButton(self, -1, "Exit")
        self.Connect = wx.Button(self, -1, "Connect")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: _406005006_Dialogo_acceso_vcenter.__set_properties
        self.SetTitle("dialog")
        self.SetSize((411, 197))
        self.text_ctrl_1.SetMinSize((300, 20))
        self.text_ctrl_2.SetMinSize((300, 20))
        self.text_ctrl_3.SetMinSize((300, 20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: _406005006_Dialogo_acceso_vcenter.__do_layout
        grid_sizer_5 = wx.FlexGridSizer(5, 2, 4, 10)
        vcenter = wx.StaticText(self, -1, "Vcenter/esxi:")
        grid_sizer_5.Add(vcenter, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_1, 0, 0, 0)
        login = wx.StaticText(self, -1, "Login:")
        grid_sizer_5.Add(login, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_2, 0, 0, 0)
        password = wx.StaticText(self, -1, "Password:")
        grid_sizer_5.Add(password, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_3, 0, 0, 0)
        puerto = wx.StaticText(self, -1, "Puerto:")
        grid_sizer_5.Add(puerto, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_4, 0, 0, 0)
        grid_sizer_5.Add(self.Exit, 0, 0, 0)
        grid_sizer_5.Add(self.Connect, 0, 0, 0)
        self.SetSizer(grid_sizer_5)
        grid_sizer_5.AddGrowableRow(1)
        self.Layout()
        # end wxGlade

# end of class _406005006_Dialogo_acceso_vcenter
